### ISSUE TITLE
ReactNativeAudioPlayer.play got 2 arguments, expected 3

### ISSUE THREAD

**Issue by jabirbarber** [ark-react-native/audio-player#1]
When doing this...

<Player url={"http://lacavewebradio.chickenkiller.com:8000/stream.mp3"} />

I get the error: ReactNativeAudioPlayer.play got 2 arguments, expected 3

Could you also guide me on how to setup audio controls from notifications on Android.
It seems when switching apps the audio just stops playing, Is there a certain setup in order to enable background play and notification tray controls?

**Comment by rodrigoscna** [comment]
Hello!

You need to set the 3rd argument of the function which is the callback function for when the player has started or not. It will return "OK" when the player started, and "ERROR" when it can't play the file.

About the notifications controls, it's not supported in this library, I made this only for a freelancer project I was working on. It's not actively maintained.

If you'd like, you could fork it and continue the development for your needs.

o/
